<?php echo $this->doctype(); ?>

<html lang="en">
<head>
<meta charset="utf-8">
        <?php echo $this->headTitle('ZF2 '. $this->translate('Skeleton Application'))->setSeparator(' - ')->setAutoEscape(false)?>

        <?php
								
								echo $this->headMeta ()->appendName ( 'viewport', 'width=device-width, initial-scale=1.0' )->appendHttpEquiv ( 'X-UA-Compatible', 'IE=edge' )?>

        <!-- Le styles -->
        <?php
								
								echo $this->headLink ( array (
										'rel' => 'shortcut icon',
										'type' => 'image/vnd.microsoft.icon',
										'href' => $this->basePath () . '/img/favicon.ico' 
								) )->prependStylesheet ( $this->basePath () . '/css/style.css' )->prependStylesheet ( $this->basePath () . '/css/bootstrap-theme.min.css' )->prependStylesheet ( $this->basePath () . '/css/bootstrap.min.css' )?>

        <!-- Scripts -->
        <?php
								
								echo $this->headScript ()->prependFile ( $this->basePath () . '/js/bootstrap.min.js' )->prependFile ( $this->basePath () . '/js/jquery.min.js' )->prependFile ( $this->basePath () . '/js/respond.min.js', 'text/javascript', array (
										'conditional' => 'lt IE 9' 
								) )->prependFile ( $this->basePath () . '/js/html5shiv.js', 'text/javascript', array (
										'conditional' => 'lt IE 9' 
								))->prependFile ( $this->basePath () . '/js/parse.min.js' );
								?>

    </head>
    
    <script type="text/javascript">
		$(document).ready(function() {		//Parse listening for News entities every 2000s
			$("#notificationsNumber").hide();
			$("#notificationsBadge").hide();
			$("#feedbacksBadge").hide();
			var counter = sessionStorage.getItem("counter");
			if(counter==null) {
				counter = 0;
				$("#notificationsNumber").hide();
				$("#notificationsBadge").hide();
			}

			

			var func = function() {
				var query = new Parse.Query(NewsObject);
				if (sessionStorage.getItem("lastDate")) {
					query.greaterThan("createdAt", sessionStorage.getItem("lastDate"));
				}
				query.find({
				  success: function(results) {
					var oldCounter = counter;
				    for (var i = 0; i < results.length; i++) { 
				      var object = results[i];
				      console.log(object.id + ' - ' + object.get('message'));
				      counter++;
				    }
				    sessionStorage.setItem("lastDate", new Date().toJSON());
				    sessionStorage.setItem("counter", counter);
				    $("#notificationsNumber").hide();
					$("#notificationsBadge").hide();
				    if(counter > 0) {
				    	$("#notificationsNumber").show().text(counter);
				    	$("#notificationsBadge").show().text(counter);	
				    }
				    if(counter > oldCounter) {
				    	document.getElementById('notificationsAudio').play();
				    }
				  },
				  error: function(error) {
				    console.log("Error: " + error.code + " " + error.message);
				  }
				})
			};

			var checkFeedbacks = function() {
				var query = new Parse.Query(FeedbackObject);
				query.descending("createdAt");
				query.find({
				  success: function(results) {
				    if(results!=null && results.length>0) {
				    	$("#feedbacksBadge").show().text(results.length);
				    }
				  },
				  error: function(error) {
				    console.log("Error: " + error.code + " " + error.message);
				  }
				})
			}
			
			$("#notificationsLink").click(function() {
				$("#notificationsNumber").hide();
				$("#notificationsBadge").hide();
				sessionStorage.setItem("counter", 0);
				counter = sessionStorage.getItem("counter");
				clearInterval(func);
			});
			
			Parse.initialize('AxoLVEF1mgZLbYGRuTa27C7ltJGhEyk5BXENud7p', 'O6jg1gIpiuwMOeuDwT9ExhmuvimXZ8DTGNQPyQNa');
			try {
				
				var NewsObject = Parse.Object.extend("News");
				var FeedbackObject = Parse.Object.extend("Feedback");

				func();
				checkFeedbacks();
				
				setInterval(func, 1500);
				setInterval(checkFeedbacks, 1000);
			}
			catch(err) {
				console.log("Error while init of Parse JS" + err);
			}
		});
    </script>
<body>
	<audio src='<?php echo $this->basePath () . "/audio/ping.mp3"; ?>' id="notificationsAudio"></audio>

	
	<nav class="navbar navbar-default navbar-fixed-top navbar-inverse" role="navigation">
	  <div class="container-fluid">
		<!-- Grupowanie "marki" i przycisku rozwijania mobilnego menu -->
		<div class="navbar-header">
		  <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-2">
			<span class="sr-only">Rozwiń nawigację</span>
			<span class="icon-bar"></span>
			<span class="icon-bar"></span>
			<span class="icon-bar"></span>
		  </button>
		  <a class="navbar-brand hidden-xs" href="#"><img src="<?php echo $this->basePath('img/logo.png') ?>" alt="EVENTOMAT"/></a>
		  <a class="navbar-brand visible-xs" href="#"><img src="<?php echo $this->basePath('img/logomini.png') ?>" alt="EVENTOMAT"/></a>
		</div>
	 	
		<!-- Grupowanie elementów menu w celu lepszego wyświetlania na urządzeniach moblinych -->
		<div class="navbar-header" style="float: right;" id="bs-example-navbar-collapse-2">
			<?php 
			if ($_SESSION ["username"] != null) {
				echo '<div style="padding-top: 10px;">';
				echo '<a id="notificationsLink" href="/application/index/notifications"><span id="notificationsNumber" class="glyphicon glyphicon-bell" style="font-size: 20px; color: white;">2</span></a>';
				echo '<div class="username">Welcome <b>' . $_SESSION ["username"] . '</b> <a href="/application/index/logout" class="btn btn-evenomat">Logout</a></div>';
				echo '</div>';
			}
			else {
				echo'<form class="navbar-form navbar-right" role="search" action="/application/index" method="POST">
				<div class="form-group">
					<input type="text" class="form-control" name="email" placeholder="Username">
				</div>
				<div class="form-group">
					<input type="password" class="form-control" name="password" placeholder="Password">
				</div>
				<button type="submit" class="btn btn-evenomat">Sign in!</button>
				</form>';
			}
			?>
			
		</div><!-- /.navbar-collapse -->
	  </div><!-- /.container-fluid -->
	</nav>
	
	<div class="container-fluid my-container">
            <?php echo $this->content; ?>
	</div>
	<!-- /container -->
        <?php echo $this->inlineScript()?>
    </body>
</html>
