<div class="row menu-text">
	<div class="col-md-4">
		<?php include('menu.html') ?>
	</div>
	<div class="col-md-8 right-box">
	
	<p class="subpage-header">Add community</p><br />
	
	<form method="POST" action="/application/index/addcommunity">
			<div class="form-group">
				<label for="email">Community name</label>
				<input type="text" class="form-control" id="commName" name="commName" placeholder="Enter community name">
			</div>
			<br />
			<button type="submit" class="btn btn-default btn-lg">Submit</button>
	</form>
	
	</div>
</div>

