<div class="jumbotron">
	<h1 class="text-success">Welcome to Eventomat!</h1>
	<p>This is the place where you manage your communities/events. Feel
		free to use!</p>
</div>

<div class="row menu-text">
	<div class="col-md-4">
		<?php include('menu.html') ?>
	</div>
	<div class="col-md-8">
	
	<?php	
		$form->setAttribute ( 'action', '/application/index/addevent');
		$form->prepare ();
	
		echo $this->form ()->openTag ( $form );
		echo $this->formRow ( $form->get ( 'eventName' ) ) . "<br />";
		echo $this->formRow ( $form->get ( 'communityId' ) ) . "<br /><br />";
		echo $this->formSubmit ( $form->get ( 'submit' ) ) . "<br />";
		echo $this->form ()->closeTag ();
	?>
	
	</div>
</div>

