<div class="row menu-text">
	<div class="col-md-4">
		<?php include('menu.html') ?>
	</div>
	<div class="col-md-8 right-box">
	
	<p class="subpage-header">Add event</p><br />
	
	<form method="POST" action="/application/index/addevent">
			<div class="form-group">
				<label for="email">Event name</label>
				<input type="text" class="form-control" id="eventName" name="eventName" placeholder="Enter event name">
			</div>
			<div class="form-group">
				<label for="password">Community ID</label><br />
				<select id="communityId" name="communityId">
					<?php 
						foreach($communities as $i=>$v) {
							echo'<option value="' . $v->getId() . '">'. $v->getName() . '</option>';
						}
					?>
				</select>
			</div>
			<br />
			<button type="submit" class="btn btn-default btn-lg">Submit</button>
		</form>
	
	</div>
</div>

