<div class="jumbotron">
	<h1 class="text-success">Welcome to Eventomat!</h1>
	<p>This is the place where you manage your communities/events. Feel
		free to use!</p>
</div>

<div class="row menu-text">
	<div class="col-md-4">
		<div class="list-group panel">
			<a href="#demo3" class="list-group-item list-group-item-success"
				data-toggle="collapse" data-parent="#MainMenu"><b>Communities</b></a>
			<div class="collapse" id="demo3">
				<a href="/application/index/addcommunity" class="list-group-item">Add</a> 
				<a href="/application/index/listcommunity" class="list-group-item" data-parent="#SubMenu1">Modify</a>
			</div>
			<a href="#demo4" class="list-group-item list-group-item-success"
				data-toggle="collapse" data-parent="#MainMenu"><b>Events</b></a>
			<div class="collapse" id="demo4">
				<a href="/application/index/addevent" class="list-group-item"">Add</a> 
				<a href="/application/index/listevent" class="list-group-item" data-parent="#SubMenu1">Modify</a>
			</div>
		</div>
	</div>
	<div class="col-md-8">
	
	<?php
		$form->setAttribute ( 'action', '/application/index/addevent');
		$form->prepare ();
	
		echo $this->form ()->openTag ( $form );
		echo $this->formRow ( $form->get ( 'eventName' ) ) . "<br />";
		echo $this->formRow ( $form->get ( 'communityId' ) ) . "<br /><br />";
		echo $this->formSubmit ( $form->get ( 'submit' ) ) . "<br />";
		echo $this->form ()->closeTag ();
	?>
	
	</div>
</div>

