<div class="jumbotron">
	<h1 class="text-success">Welcome to Eventomat!</h1>
	<p>This is the place where you manage your communities/events. Feel
		free to use!</p>
</div>

<div class="row menu-text">
	<div class="col-md-4">
		<?php include('menu.html') ?>
	</div>
	<div class="col-md-8">
	
	<h3><b>Event name: 
	<?php
		echo $event->getName();
	?>
	</b></h3><br />
	<h4>Agenda</h4><br />
	<ul class="list-group">
	<?php 
		foreach($schedules1 as $i=>$v) {
			echo '<li class="list-group-item">'. $v->getName() .', <b>'. $v->getDay() .', '.$v->getTime() . '</b><span class="badge"><a href="/application/index/scheduledelete/'.$v->getId().'">Delete</a></span></li>';
		}
	?>
	</ul>
	<ul class="list-group">
	<?php 
		foreach($schedules2 as $i=>$v) {
			echo '<li class="list-group-item">'. $v->getName() .', <b>'. $v->getDay() .', '.$v->getTime() . '</b><span class="badge"><a href="/application/index/scheduledelete/'.$v->getId().'">Delete</a></span></li>';
		}
	?>
	</ul>
	<ul class="list-group">
	<?php 
		foreach($schedules3 as $i=>$v) {
			echo '<li class="list-group-item">'. $v->getName() .', <b>'. $v->getDay() .', '.$v->getTime() . '</b><span class="badge"><a href="/application/index/scheduledelete/'.$v->getId().'">Delete</a></span></li>';
		}
	?>
	</ul>
	</div>
</div>

