<div class="row menu-text">
	<div class="col-md-4">
		<?php include('menu.html') ?>
	</div>
	<div class="col-md-8 right-box">
	
	<p class="subpage-header">Events</p>
	
	<h3><b>Event name: 
	<?php
		echo $event->getName();
	?>
	</b></h3><br />
	<h3>Agenda</h3><br />
	<ul class="list-group">
	<?php 
		foreach($schedules1 as $i=>$v) {
			echo '<li class="list-group-item">'. $v->getName() .', <b>'. $v->getDay() .', '.$v->getTime() . '</b><span class="badge"><a href="/application/index/scheduledelete/'.$v->getId().'">Delete</a></span></li>';
		}
	?>
	</ul>
	<ul class="list-group">
	<?php 
		foreach($schedules2 as $i=>$v) {
			echo '<li class="list-group-item">'. $v->getName() .', <b>'. $v->getDay() .', '.$v->getTime() . '</b><span class="badge"><a href="/application/index/scheduledelete/'.$v->getId().'">Delete</a></span></li>';
		}
	?>
	</ul>
	<ul class="list-group">
	<?php 
		foreach($schedules3 as $i=>$v) {
			echo '<li class="list-group-item">'. $v->getName() .', <b>'. $v->getDay() .', '.$v->getTime() . '</b><span class="badge"><a href="/application/index/scheduledelete/'.$v->getId().'">Delete</a></span></li>';
		}
	?>
	</ul>
	</div>
</div>

