<div class="row">

	<div class="col-md-12">
		<h1>Welcome in Eventomat!</h1>
		<form method="POST" action="/application/index">
			<div class="form-group">
				<label for="email">Email address</label> <input
					type="email" class="form-control" id="email" name="email"
					placeholder="Enter email">
			</div>
			<div class="form-group">
				<label for="password">Password</label> <input
					type="password" class="form-control" id="password" name="password"
					placeholder="Password">
			</div>
			<button type="submit" class="btn btn-default">Submit</button>
		</form>
	</div>

</div>
