<div class="container">
		<div class="row" style="padding-top: 40px;">
			<div class="col-lg-4">
				<img src="/img/phone.png" id="phone" class="center-block"/>
				<div class="text-center" id="evtext">
					<h3><strong>Eventomat</strong> enables you to <strong>manage</strong> events effectively, <strong>broadcast</strong> important messages across different channels and <strong>collect feedback</strong> from attendees - all in one place and in real time.<br />
					Stop thinking about website, mobiles, social media and <strong>rock your event</strong> with us!</h3>
                </div>
			</div>
			<div class="col-lg-6 col-lg-offset-2">
				<h1 class="text-center">Registration</h1>
				<div class="form-group">
					<div class="input-group">
						<span class="input-group-addon danger"><span class="glyphicon glyphicon-user"></span></span>
						<input type="text" name="first_name" id="first_name" class="form-control input-lg" placeholder="First Name">
					</div>
				</div>			
				<div class="form-group">
					<div class="input-group">
						<span class="input-group-addon danger"><span class="glyphicon glyphicon-user"></span></span>
						<input type="text" name="last_name" id="last_name" class="form-control input-lg" placeholder="Last Name">
					</div>
				</div>				
				<div class="form-group">
					<div class="input-group">
						<span class="input-group-addon danger"><span class="glyphicon glyphicon-envelope"></span></span>
						<input type="email" name="email" id="email" class="form-control input-lg" placeholder="Email Address">
					</div>
				</div>			
				<div class="form-group">
					<div class="input-group">
						<span class="input-group-addon danger"><span class="glyphicon glyphicon-lock"></span></span>
						<input type="password" name="password" id="password" class="form-control input-lg" placeholder="Password">
					</div>
				</div>	
				<div class="form-group">
					<div class="input-group">
						<span class="input-group-addon danger"><span class="glyphicon glyphicon-lock"></span></span>
						<input type="password" name="password_confirmation" id="password_confirmation" class="form-control input-lg"placeholder="Confirm Password">
					</div>
				</div>
				<button type="submit" class="btn btn-evenomat btn-lg btn-block">Rock your event!</button>
			</div>
		</div>
	</div>
