<div class="row menu-text">
	<div class="col-md-4">
		<?php include('menu.html') ?>
	</div>
	<div class="col-md-8 right-box">
	
	<p class="subpage-header">Events</p>
	
		<ul class="list-group">
		<?php
			foreach($items as $i=>$v) {
				echo '<li class="list-group-item">'. $v->getName() .'<span class="badge"><a href="/application/index/eventdetails/' . $v->getId() . '">Details</a></span><span class="badge">Delete</span></li>';
			}
		?>
	</ul>
	</div>
</div>

