<div class="jumbotron">
	<h1 class="text-success">Welcome to Eventomat!</h1>
	<p>This is the place where you manage your communities/events. Feel
		free to use!</p>
</div>

<div class="row menu-text">
	<div class="col-md-4">
		<?php include('menu.html') ?>
	</div>
	<div class="col-md-8">
		<ul class="list-group">
		<?php
			foreach($items as $i=>$v) {
				echo '<li class="list-group-item">'. $v->getName() .'<span class="badge">Delete</span></li>';
			}
		?>
	</ul>
	</div>
</div>

