<div class="row menu-text">
	<div class="col-md-4 right-box">
		<?php include('menu.html') ?>
	</div>
	<div class="col-md-8">

		<div class="row right-box" style="width: 99%; float: right;">
		
			<p class="subpage-header" style="padding-left: 10px;">Send push notification</p>

			<div class="col-md-12">
				<form method="POST" action="/application/index/sendpush">
					<div class="form-group">
						<label for="message">Message to send</label><br />
						<textarea rows="8" cols="40" id="message" name="message">Message to send...</textarea>
					</div>
					
					<div class="form-group">
						<input type="checkbox" id="sendTwitter" name="sendTwitter" /> <b>Send on Twitter</b>
					</div>
					<div class="form-group">
						<input type="checkbox" id="sendTwitter" name="sendTwitter" /> <b>Send on Facebook</b>
					</div>
					
					<div class="form-group">
						<button type="submit" class="btn btn-default btn-lg">Submit</button>
					</div>
				</form>
			</div>
		</div>
	</div>
</div>