<div class="jumbotron">
	<h1 class="text-success">Welcome to Eventomat!</h1>
	<p>This is the place where you manage your communities/events. Feel
		free to use!</p>
</div>

<div class="row menu-text">
	<div class="col-md-4">
		<?php include('menu.html') ?>
	</div>
	<div class="col-md-8">

		<div class="row">

			<div class="col-md-12">
				<form method="POST" action="/application/index/sendpush">
					<div class="form-group">
						<label for="message">Message to send</label>
						<textarea rows="8" cols="40" id="message" name="message">Message to send...</textarea>
					</div>
					<div class="form-group">
						<button type="submit" class="btn btn-default">Submit</button>
					</div>
				</form>
			</div>
		</div>
	</div>
</div>

